import type { Match } from './models'

export const mockMatch: Match = {
  id: 1,
  first: 'Даня',
  second: 'Миша',
  score: { first: 1, second: 1 },
  status: 'active',
  sets: [
    {
      id: 1,
      score: { first: 11, second: 2 },
      winner: 'first',
      firstServer: 'first',
      server: 'none',
      setStat: [],
      status: 'completed',
    },
    {
      id: 2,
      score: { first: 2, second: 11 },
      winner: 'second',
      firstServer: 'second',
      server: 'none',
      setStat: [],
      status: 'completed',
    },
    {
      id: 3,
      score: { first: 0, second: 0 },
      winner: 'none',
      firstServer: 'first',
      server: 'first',
      setStat: [],
      status: 'active',
    },
    {
      id: 4,
      score: { first: 0, second: 0 },
      winner: 'none',
      firstServer: 'second',
      server: 'none',
      setStat: [],
      status: 'not_started',
    },
    {
      id: 5,
      score: { first: 0, second: 0 },
      winner: 'none',
      firstServer: 'first',
      server: 'none',
      setStat: [],
      status: 'not_started',
    },
  ],
}
